name: flutter_vlc_player_platform_interface
description: A common platform interface for the flutter vlc player plugin.
homepage: https://github.com/solid-software/flutter_vlc_player
version: 2.0.4

environment:
  sdk: '>=3.4.3 <4.0.0'
  #flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  #meta: ^1.8.0
  plugin_platform_interface: 2.1.8  #^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: 5.4.4 #^5.3.2
  solid_lints: 0.1.5 #^0.0.18
